// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Userrpc.proto

package org.learning.protobufrpc.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf service {@code protobuf.UserService}
   */
  public static abstract class UserService
      implements com.google.protobuf.Service {
    protected UserService() {}

    public interface Interface {
      /**
       * <code>rpc getUser(.User) returns (.User);</code>
       */
      public abstract void getUser(
          com.google.protobuf.RpcController controller,
          org.learning.protobufrpc.proto.UserProtos.User request,
          com.google.protobuf.RpcCallback<org.learning.protobufrpc.proto.UserProtos.User> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new UserService() {
        @java.lang.Override
        public  void getUser(
            com.google.protobuf.RpcController controller,
            org.learning.protobufrpc.proto.UserProtos.User request,
            com.google.protobuf.RpcCallback<org.learning.protobufrpc.proto.UserProtos.User> done) {
          impl.getUser(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getUser(controller, (org.learning.protobufrpc.proto.UserProtos.User)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.learning.protobufrpc.proto.UserProtos.User.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.learning.protobufrpc.proto.UserProtos.User.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getUser(.User) returns (.User);</code>
     */
    public abstract void getUser(
        com.google.protobuf.RpcController controller,
        org.learning.protobufrpc.proto.UserProtos.User request,
        com.google.protobuf.RpcCallback<org.learning.protobufrpc.proto.UserProtos.User> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.learning.protobufrpc.proto.UserProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getUser(controller, (org.learning.protobufrpc.proto.UserProtos.User)request,
            com.google.protobuf.RpcUtil.<org.learning.protobufrpc.proto.UserProtos.User>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.learning.protobufrpc.proto.UserProtos.User.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.learning.protobufrpc.proto.UserProtos.User.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.learning.protobufrpc.proto.UserProto.UserService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getUser(
          com.google.protobuf.RpcController controller,
          org.learning.protobufrpc.proto.UserProtos.User request,
          com.google.protobuf.RpcCallback<org.learning.protobufrpc.proto.UserProtos.User> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.learning.protobufrpc.proto.UserProtos.User.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.learning.protobufrpc.proto.UserProtos.User.class,
            org.learning.protobufrpc.proto.UserProtos.User.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.learning.protobufrpc.proto.UserProtos.User getUser(
          com.google.protobuf.RpcController controller,
          org.learning.protobufrpc.proto.UserProtos.User request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.learning.protobufrpc.proto.UserProtos.User getUser(
          com.google.protobuf.RpcController controller,
          org.learning.protobufrpc.proto.UserProtos.User request)
          throws com.google.protobuf.ServiceException {
        return (org.learning.protobufrpc.proto.UserProtos.User) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.learning.protobufrpc.proto.UserProtos.User.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:protobuf.UserService)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rUserrpc.proto\022\010protobuf\032\nUser.proto2&\n" +
      "\013UserService\022\027\n\007getUser\022\005.User\032\005.UserB.\n" +
      "\036org.learning.protobufrpc.protoB\tUserPro" +
      "to\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.learning.protobufrpc.proto.UserProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
